In [1]:
import numpy as np

## Creating array

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [7]:
a = np.arange(1,11)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
a = np.full(10,10)
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [12]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Random numbers generation

In [15]:
a = np.random.randint(1,100,10)
a

array([62, 92,  2, 89, 25, 84, 64, 16, 76, 66])

In [16]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 4, 9],
       [5, 1, 3],
       [4, 7, 2]])

### Linspace

In [20]:
a, step = np.linspace(1,10,5, retstep=True)
a, step

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [22]:
a = np.linspace(1,50,10)
a

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

### Attributes of ndarray

In [27]:
a = np.random.randint(1,10,(3,3), dtype='int64')

In [29]:
a.ndim, a.size, a.dtype, a.shape

(2, 9, dtype('int64'), (3, 3))

### Indexing and slicing

In [30]:
a = np.random.randint(1,10,(5,5))

In [32]:
a

array([[5, 9, 6, 8, 1],
       [4, 1, 3, 2, 1],
       [7, 4, 2, 4, 2],
       [4, 4, 9, 6, 8],
       [7, 6, 1, 3, 8]])

In [31]:
a[0,0]

5

In [33]:
a[4] 

array([7, 6, 1, 3, 8])

In [34]:
a[:,4]

array([1, 1, 2, 8, 8])

In [36]:
a[2:4,3:5]

array([[4, 2],
       [6, 8]])

In [37]:
a[1:3,1:4]

array([[1, 3, 2],
       [4, 2, 4]])

In [39]:
a[-1,-1] # Last col in last row 

8

In [41]:
a[-2:,-2:]

array([[6, 8],
       [3, 8]])

In [43]:
a

array([[5, 9, 6, 8, 1],
       [4, 1, 3, 2, 1],
       [7, 4, 2, 4, 2],
       [4, 4, 9, 6, 8],
       [7, 6, 1, 3, 8]])

In [42]:
a[-1::-1]

array([[7, 6, 1, 3, 8],
       [4, 4, 9, 6, 8],
       [7, 4, 2, 4, 2],
       [4, 1, 3, 2, 1],
       [5, 9, 6, 8, 1]])

In [44]:
### index by array

In [46]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a[[3,6,9]]

array([ 4,  7, 10])

In [48]:
a[[-1,-5,0]]

array([10,  6,  1])

In [64]:
a = np.random.randint(1,10,(5,5))
a

array([[6, 5, 6, 3, 4],
       [9, 2, 9, 6, 2],
       [9, 9, 2, 8, 2],
       [4, 9, 6, 9, 4],
       [6, 2, 2, 2, 1]])

In [68]:
a [[0,3],[0,3]]

array([6, 9])

In [56]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Iterate 

In [61]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 7, 9],
       [7, 5, 3],
       [8, 5, 7]])

In [62]:
for r in a:
    for c in r:
         print(c)

5
7
9
7
5
3
8
5
7


In [57]:
a = np.arange(10)
for n in a:
    print(n)

0
1
2
3
4
5
6
7
8
9


### Boolean Indexing

In [2]:
a = np.random.randint(1,100,5)
a

array([55,  7, 75, 57, 19])

In [3]:
b = a [ [True,False,True,False,False]]

In [4]:
b

array([55, 75])

In [5]:
b[0] = 50

In [6]:
a

array([55,  7, 75, 57, 19])

In [7]:
b

array([50, 75])

In [18]:
a = np.random.randint(1,100,10)
a

array([43, 66, 36, 89, 97, 14, 93, 96, 66,  2])

In [19]:
evens = a % 2 == 0 
evens

array([False,  True,  True, False, False,  True, False,  True,  True,
        True])

In [16]:
a [ evens ]

array([84, 76, 32, 28, 46, 20, 42, 18, 26,  4, 50, 14, 66, 82])

In [12]:
a = np.random.randint(1,100, (5,5))
a

array([[84, 27, 76, 49, 11],
       [32, 63, 27, 77, 28],
       [46, 20, 42, 18, 27],
       [26,  4, 50,  3, 27],
       [14, 66, 37,  5, 82]])

In [13]:
a % 2 == 0 

array([[ True, False,  True, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True, False, False,  True]])

In [20]:
a [ a > 50 ]

array([66, 89, 97, 93, 96, 66])

### Array Operations

In [21]:
a = np.array([1,2,3,4,5])

In [24]:
b = a + 10

In [25]:
b

array([11, 12, 13, 14, 15])

In [26]:
b -= 5

In [27]:
b

array([ 6,  7,  8,  9, 10])

### Methods of ndarray

In [30]:
a.mean(), a.sum(), a.std()

(3.0, 15, 1.4142135623730951)

In [31]:
a.all()

True

In [37]:
print(a % 2 == 0)
(a % 2 == 0).all(), (a % 2 == 0).any()

[False  True False  True False]


(False, True)

In [36]:
(a != 0).all()

True

In [38]:
np.zeros(10).any()

False

In [39]:
a.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [40]:
a.argmax()

4

In [41]:
a

array([1, 2, 3, 4, 5])

In [43]:
a.searchsorted(3)

2

In [44]:
a.tolist()

[1, 2, 3, 4, 5]

In [46]:
a[0] = 7
a[3] = 9

In [47]:
a

array([7, 2, 3, 9, 5])

In [48]:
sorted(a)

[2, 3, 5, 7, 9]

In [49]:
a.sort()

In [50]:
a

array([2, 3, 5, 7, 9])

#### 2D array

In [52]:
a = np.random.randint(1,10,(3,3))
a

array([[8, 2, 6],
       [8, 2, 8],
       [4, 1, 4]])

In [53]:
a.sum()

43

In [54]:
a.sum(axis=1)

array([16, 18,  9])

In [55]:
a.sum(axis=0)

array([20,  5, 18])

In [56]:
a.cumsum(axis=1)

array([[ 8, 10, 16],
       [ 8, 10, 18],
       [ 4,  5,  9]], dtype=int32)

### Copy vs. View 

In [57]:
a=np.arange(1,11)

In [58]:
b = a[5:]  # View into a 

In [59]:
b

array([ 6,  7,  8,  9, 10])

In [60]:
b[0] = 20

In [61]:
b

array([20,  7,  8,  9, 10])

In [62]:
a

array([ 1,  2,  3,  4,  5, 20,  7,  8,  9, 10])

In [63]:
b[:] = 0

In [64]:
a

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])

In [65]:
b[:2] = [10,20]

In [67]:
c= b[:3]

In [68]:
c[0] = 100

In [69]:
a

array([  1,   2,   3,   4,   5, 100,  20,   0,   0,   0])

In [70]:
id(a), id(b)

(2556523718576, 2556523042176)

### Stacking and splitting 

In [11]:
a1 = np.arange(4).reshape(2,2)
a1

array([[0, 1],
       [2, 3]])

In [12]:
a2 = np.arange(10,14).reshape(2,2)
a2

array([[10, 11],
       [12, 13]])

In [13]:
np.hstack( (a1,a2))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [18]:
np.concatenate((a1,a2), axis=1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [21]:
a = np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [22]:
np.vsplit(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [23]:
np.hsplit(a,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27],
        [31, 32, 33]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30],
        [34, 35, 36]])]

In [24]:
np.vsplit(a, (1,4))   # Split at row 1 and row 4 

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

### Reshaping array

In [28]:
a = np.random.randint(1,10, (3,3))
a

array([[7, 5, 7],
       [4, 7, 9],
       [5, 3, 6]])

In [33]:
ar  = a.ravel()

In [34]:
ar[0] = 10

In [35]:
a

array([[10,  5,  7],
       [ 4,  7,  9],
       [ 5,  3,  6]])

In [32]:
a.flatten('F')

array([7, 4, 5, 5, 7, 3, 7, 9, 6])

In [60]:
a = np.random.randint(1,10, (4,5))
a

array([[1, 1, 3, 9, 2],
       [7, 1, 2, 9, 7],
       [1, 4, 1, 2, 3],
       [2, 3, 6, 3, 3]])

In [61]:
a.reshape(5,-1)

array([[1, 1, 3, 9],
       [2, 7, 1, 2],
       [9, 7, 1, 4],
       [1, 2, 3, 2],
       [3, 6, 3, 3]])

In [39]:
a.reshape(2,10)

array([[8, 6, 1, 2, 5, 5, 5, 8, 1, 4],
       [8, 8, 1, 1, 4, 4, 3, 7, 7, 9]])

In [40]:
a.T

array([[8, 5, 8, 4],
       [6, 5, 8, 3],
       [1, 8, 1, 7],
       [2, 1, 1, 7],
       [5, 4, 4, 9]])

In [41]:
a.transpose()

array([[8, 5, 8, 4],
       [6, 5, 8, 3],
       [1, 8, 1, 7],
       [2, 1, 1, 7],
       [5, 4, 4, 9]])

In [42]:
a

array([[8, 6, 1, 2, 5],
       [5, 5, 8, 1, 4],
       [8, 8, 1, 1, 4],
       [4, 3, 7, 7, 9]])

In [43]:
a.resize(2,10)

In [44]:
a

array([[8, 6, 1, 2, 5, 5, 5, 8, 1, 4],
       [8, 8, 1, 1, 4, 4, 3, 7, 7, 9]])

In [45]:
avg_a = np.mean(a)

In [47]:
a[a > avg_a]

array([8, 6, 5, 5, 5, 8, 8, 8, 7, 7, 9])

In [53]:
a%2 == 0 

array([[ True,  True, False,  True, False, False, False,  True, False,
         True],
       [ True,  True, False, False,  True,  True, False, False, False,
        False]])

In [51]:
(a % 2 == 0).sum(axis=1)  # No. of even numbers in each row 

array([5, 4])

In [52]:
(a % 2 == 0).sum(axis=0)

array([2, 2, 0, 1, 1, 1, 0, 1, 0, 1])

In [54]:
np.sum(a%2 == 0,axis=1)  # No. of even numbers in each row 

array([5, 4])

### Linear Algebra

In [58]:
a = np.random.randint(1,10, (5,5))
a

array([[2, 4, 5, 3, 8],
       [4, 3, 7, 1, 2],
       [2, 3, 2, 6, 9],
       [5, 1, 9, 3, 8],
       [7, 6, 7, 4, 3]])

In [59]:
np.linalg.inv(a)

array([[ 0.2692703 , -1.11921891, -0.5282631 ,  0.38746146,  0.57965057],
       [ 0.24768756, -0.02569373, -0.09660843, -0.16649538,  0.09044193],
       [-0.26618705,  0.82014388,  0.32374101, -0.16546763, -0.36690647],
       [-0.62898253,  1.01130524,  0.72250771, -0.28674203, -0.39979445],
       [ 0.336074  , -0.5991778 , -0.29290853,  0.19732785,  0.18910586]])