In [1]:
import numpy as np

## Creating array

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [7]:
a = np.arange(1,11)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
a = np.full(10,10)
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [12]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Random numbers generation

In [15]:
a = np.random.randint(1,100,10)
a

array([62, 92,  2, 89, 25, 84, 64, 16, 76, 66])

In [16]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 4, 9],
       [5, 1, 3],
       [4, 7, 2]])

### Linspace

In [20]:
a, step = np.linspace(1,10,5, retstep=True)
a, step

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [22]:
a = np.linspace(1,50,10)
a

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

### Attributes of ndarray

In [27]:
a = np.random.randint(1,10,(3,3), dtype='int64')

In [29]:
a.ndim, a.size, a.dtype, a.shape

(2, 9, dtype('int64'), (3, 3))

### Indexing and slicing

In [30]:
a = np.random.randint(1,10,(5,5))

In [32]:
a

array([[5, 9, 6, 8, 1],
       [4, 1, 3, 2, 1],
       [7, 4, 2, 4, 2],
       [4, 4, 9, 6, 8],
       [7, 6, 1, 3, 8]])

In [31]:
a[0,0]

5

In [33]:
a[4] 

array([7, 6, 1, 3, 8])

In [34]:
a[:,4]

array([1, 1, 2, 8, 8])

In [36]:
a[2:4,3:5]

array([[4, 2],
       [6, 8]])

In [37]:
a[1:3,1:4]

array([[1, 3, 2],
       [4, 2, 4]])

In [39]:
a[-1,-1] # Last col in last row 

8

In [41]:
a[-2:,-2:]

array([[6, 8],
       [3, 8]])

In [43]:
a

array([[5, 9, 6, 8, 1],
       [4, 1, 3, 2, 1],
       [7, 4, 2, 4, 2],
       [4, 4, 9, 6, 8],
       [7, 6, 1, 3, 8]])

In [42]:
a[-1::-1]

array([[7, 6, 1, 3, 8],
       [4, 4, 9, 6, 8],
       [7, 4, 2, 4, 2],
       [4, 1, 3, 2, 1],
       [5, 9, 6, 8, 1]])

In [44]:
### index by array

In [46]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a[[3,6,9]]

array([ 4,  7, 10])

In [48]:
a[[-1,-5,0]]

array([10,  6,  1])

In [64]:
a = np.random.randint(1,10,(5,5))
a

array([[6, 5, 6, 3, 4],
       [9, 2, 9, 6, 2],
       [9, 9, 2, 8, 2],
       [4, 9, 6, 9, 4],
       [6, 2, 2, 2, 1]])

In [68]:
a [[0,3],[0,3]]

array([6, 9])

In [56]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Iterate 

In [61]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 7, 9],
       [7, 5, 3],
       [8, 5, 7]])

In [62]:
for r in a:
    for c in r:
         print(c)

5
7
9
7
5
3
8
5
7


In [57]:
a = np.arange(10)
for n in a:
    print(n)

0
1
2
3
4
5
6
7
8
9
